service: cognito-backend

provider:
  name: aws
  runtime: nodejs12.x

functions:
  hello:
    handler: handler.people
    events:
      - http:
          path: people
          method: get
          cors: true
          integration: lambda
          authorizer:
            arn: arn:aws:cognito-idp:xx-xxxxx-n:nnnnnnnnnn:userpool/xx-xxxx-n_xxxxxxx
            claims:
              - email
