GET https://b4e1ogwvkc.execute-api.us-east-1.amazonaws.com/dev/people
Authorization: Bearer eyJraWQiOiJrK05OK280NXorVkhmV1RNREorQ0lDaUNJNXFxbU5MME9cL1BMQ3lSUjJ0bz0iLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiI0YmRlY2ExZi0wZDgwLTRiYzAtYjdiZi1kOTJkNGI3YjFjMDIiLCJhdWQiOiI0OW1saW1rNW5vY2JvMTJmaGxhNG02ZGw4MSIsImVtYWlsX3ZlcmlmaWVkIjp0cnVlLCJldmVudF9pZCI6IjI3ODE3YzMxLWYxOWItNDdiYS1hM2ZkLWI5MTRkNjM0YTAyNyIsInRva2VuX3VzZSI6ImlkIiwiYXV0aF90aW1lIjoxNTg1MjM4OTcwLCJpc3MiOiJodHRwczpcL1wvY29nbml0by1pZHAudXMtZWFzdC0xLmFtYXpvbmF3cy5jb21cL3VzLWVhc3QtMV9XQTlaUmo4WjgiLCJjb2duaXRvOnVzZXJuYW1lIjoiZmFicmljaW8zIiwiZXhwIjoxNTg1MjQyNTcwLCJpYXQiOjE1ODUyMzg5NzAsImVtYWlsIjoiZmFicmljaW8zQG1haWxpbmF0b3IuY29tIn0.h9Jm03UatIzbyFBGgl_zauFSS4wbTrAumJk7ANplOkCQkkW2K56-5N2waTaZdju0qH0zQ70GDnMcOGw2sHmVDREYS8BpzUOBnYbpwLYSphoYkl30K3sqv73yF68Xnbxdjg9GTHAbEALuUxfKGZZ7Z8ujoKK8ms03mZT44ax_OG9qo2VuDb-2NRuWpuBMCpLtf60_ujAA5yvCU5-SK6y_vNsl2soOYCFW9HJOdXI4y9Q4ycTmxRSWn1JTBUr2gKpnQzS7tH3ZwiHiNSTiw5QvyBcStV3nTboIJZNubUlTOIhQ5Fw34f86e93OpbcIkR0gglz7aamBPvZfNOCqt-i7eQ

###
